#!/usr/bin/env python3
"""Builds libs/kjv.b64.js — the KJV text DarkPDF shows in verse tooltips.

Source: scrollmapper/bible_databases (public domain KJV, 1769 text).
Run this only to regenerate the data file; the output is committed.

    python tools/build_kjv.py

The output is a .js file assigning gzipped-then-base64 text to a global,
rather than a plain .gz. That is not about compression — it is so the dev
index.html works when opened straight off disk. fetch() is blocked for
file:// origins by CORS, but loading a <script> is not, so kjv.js pulls this
in on demand with an injected script element and the reader works by
double-clicking index.html, with no server involved.

Inner format (chosen over JSON to avoid ~1MB of structural overhead):

    book \x1e chapter \x1e chapter ...        <- books joined by \x1d
    verse \x1f verse \x1f verse ...           <- verses within a chapter

Books appear in canonical order. None of the three ASCII separators occur
anywhere in the KJV text itself, so the split is unambiguous.
"""
import base64, gzip, io, json, pathlib, sys, urllib.request

SRC = ("https://raw.githubusercontent.com/scrollmapper/bible_databases"
       "/master/formats/json/KJV.json")

# The source spells numbered books with Roman numerals; DarkPDF keys off
# modern names, which is also what the reference parser resolves to.
RENAME = {
    "I Samuel": "1 Samuel", "II Samuel": "2 Samuel",
    "I Kings": "1 Kings", "II Kings": "2 Kings",
    "I Chronicles": "1 Chronicles", "II Chronicles": "2 Chronicles",
    "I Corinthians": "1 Corinthians", "II Corinthians": "2 Corinthians",
    "I Thessalonians": "1 Thessalonians", "II Thessalonians": "2 Thessalonians",
    "I Timothy": "1 Timothy", "II Timothy": "2 Timothy",
    "I Peter": "1 Peter", "II Peter": "2 Peter",
    "I John": "1 John", "II John": "2 John", "III John": "3 John",
    "Revelation of John": "Revelation",
}

GS, RS, US = "\x1d", "\x1e", "\x1f"   # book, chapter, verse separators

# Sanity anchors — a silently truncated download must not ship.
EXPECTED_VERSES = 31102
EXPECTED_BOOKS = 66
SPOT_CHECKS = [
    ("Genesis", 1, 1, "In the beginning God created the heaven and the earth."),
    ("John", 3, 16, "For God so loved the world"),
    ("Isaiah", 9, 10, "The bricks are fallen down"),
    ("Revelation", 22, 21, "The grace of our Lord Jesus Christ be with you all. Amen."),
]


def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    cache = root / "tools" / ".kjv_source.json"

    if cache.exists():
        print(f"using cached source ({cache.stat().st_size:,} bytes)")
        raw = cache.read_text(encoding="utf-8")
    else:
        print(f"downloading {SRC}")
        with urllib.request.urlopen(SRC, timeout=180) as r:
            raw = r.read().decode("utf-8")
        cache.write_text(raw, encoding="utf-8")

    data = json.loads(raw)
    books = data["books"]
    if len(books) != EXPECTED_BOOKS:
        sys.exit(f"expected {EXPECTED_BOOKS} books, got {len(books)}")

    out, index, total = [], {}, 0
    for b in books:
        name = RENAME.get(b["name"], b["name"])
        chapters = []
        for c in b["chapters"]:
            verses = [v["text"].strip() for v in c["verses"]]
            for t in verses:
                if any(sep in t for sep in (GS, RS, US)):
                    sys.exit(f"separator collision in {name} {c['chapter']}")
            chapters.append(US.join(verses))
            total += len(verses)
        index[name] = [len(ch.split(US)) for ch in chapters]
        out.append(name + RS + RS.join(chapters))

    if total != EXPECTED_VERSES:
        sys.exit(f"expected {EXPECTED_VERSES} verses, got {total}")

    text = GS.join(out)

    # Verify spot checks against the encoded form, not the parsed JSON, so a
    # bug in the encoder itself gets caught here too.
    decoded = {}
    for rec in text.split(GS):
        parts = rec.split(RS)
        decoded[parts[0]] = [ch.split(US) for ch in parts[1:]]
    for bk, ch, vs, prefix in SPOT_CHECKS:
        got = decoded[bk][ch - 1][vs - 1]
        if not got.startswith(prefix):
            sys.exit(f"spot check failed: {bk} {ch}:{vs} -> {got[:60]!r}")
        print(f"  ok  {bk} {ch}:{vs}")

    # mtime=0 keeps the output byte-identical between runs.
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as f:
        f.write(text.encode("utf-8"))
    gz = buf.getvalue()
    b64 = base64.b64encode(gz).decode("ascii")

    dest = root / "libs" / "kjv.b64.js"
    dest.parent.mkdir(exist_ok=True)
    dest.write_text(
        "/* Generated by tools/build_kjv.py - do not edit.\n"
        f"   King James Version, public domain. {total:,} verses, gzip+base64.\n"
        "   Loaded on demand by kjv.js; see that file for the inner format. */\n"
        f'window.__KJV_B64__="{b64}";\n',
        encoding="utf-8", newline="\n")

    print(f"\n{len(books)} books, {total:,} verses, {len(text):,} chars raw")
    print(f"gzip {len(gz):,} bytes -> base64 {len(b64):,}")
    print(f"libs/kjv.b64.js written ({dest.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
